# Generated by Django 6.0.3 on 2026-03-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_options_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('free', '자유'), ('travel', '여행'), ('study', '공부'), ('food', '음식')], default='free', max_length=20, verbose_name='카테고리'),
        ),
    ]
